### ISSUE TITLE
The Huntsman Elo Rating 

### ISSUE THREAD

**Issue by ginkgo20** [joergoster/Stockfish-old#10]
http://ccrl.chessdom.com/ccrl/4040/rating_list_all.html

I couldn't find the Matefish rating.

**Comment by joergoster** [comment]
Matefish can't play games and thus has no rating.
I'm not aware of any rating list testing The Huntsman.

**Comment by penguingim1** [comment]
Do you have any chess engine in CCRL Ranking?

e.g : moonfish ,matefish , ...fish

**Comment by ginkgo20** [comment]
@joergoster You are the best and most experienced Stockfish author, your chess engine should be at least in the top 10 world chess rankings.If you are willing, we can write the most powerful chess engine in the world.

**Comment by joergoster** [comment]
@ginkgo20 I'm just a layman programmer, not a professional one. Just learning by doing most of the times.  I'm afraid you have to write the most powerful chess engine all on your own! There's no point in buttering me up either. There is no such thing like _my_ chess engine!

One last time: STOP pinging me and abusing my repositories! Go and get some help!

**Comment by ginkgo20** [comment]
https://github.com/joergoster/Stockfish-old/assets/132969765/6df4dc1a-966b-4899-9e26-7a1559fb9ee3
