### ISSUE TITLE
which StockFish version used ?

### ISSUE THREAD

**Issue by tissatussa** [joergoster/Stockfish-old#12]
hi,

i just found your MoJo v1.5 version of SF, with its custom options.
i managed to compile the source from the asset ZIP and the resulting binary runs fine.
[ i'm on Xubuntu 22.04 ]

i wonder which SF version was used.

btw. i noticed since a few years SF no longer has a version number, the info of its `uci` command only shows a date, am i right ? Same with MoJo v1.5

will / can you ever update your MoJo source files by using newer SF code ?
or does such update take a lot of work to apply your MoJo settings ?

**Comment by joergoster** [comment]
@tissatussa Hi, this modified version is rather outdated. It is based an version more than 2 years ago.

Right now, I'm updating The Huntsman. Maybe I will do the same with MoJo. I can't tell for sure atm.

**Comment by tissatussa** [comment]
about MoJo : i like the option "Minimum Thinking Time" !
