### ISSUE TITLE
Erratic eval

### ISSUE THREAD

**Issue by 0zymandia2** [joergoster/Stockfish-old#6]
Hi,

I don't know if Arno reported this to you, but I noticed months ago that it doesn't work as intended.

It may give a LaskerDraw score when it can't be forced or miss it when it can, it also changes the sign of the evaluation, so it may look like the wrong side is up, and may only reports a LaskerDraw score for the side losing. Take this position:
8/8/8/4Rb2/5k1p/7P/6K1/8 w - - 0 84
Here white refuses to take the Bishop and gives a "winning"score despite that. When looking at the PV, really strange things await.

**Comment by joergoster** [comment]
Thanks.
Probably a bug. I will look into it asap.

**Comment by joergoster** [comment]
@0zymandia2 Did you use the lest version from March 14, 2021? See https://github.com/joergoster/Stockfish/releases/tag/v0.2
This is what I get:

position fen 8/8/8/4Rb2/5k1p/7P/6K1/8 w - - 0 84
d
```

 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 8
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 7
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 6
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | R | b |   |   | 5
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   | k |   | p | 4
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   | P | 3
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   | K |   | 2
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   | 1
 +---+---+---+---+---+---+---+---+
   a   b   c   d   e   f   g   h

```
Fen: 8/8/8/4Rb2/5k1p/7P/6K1/8 w - - 0 84
Key: A295A93D8907D0DE
Checkers: 
go movetime 10000
info string NNUE evaluation using nn-62ef826d1a6d.nnue enabled
info depth 1 seldepth 1 multipv 1 score cp 34 nodes 36 nps 18000 tbhits 0 time 2 pv e5a5 f5e4 g2f2
info depth 2 seldepth 3 multipv 1 score cp 98 nodes 108 nps 54000 tbhits 0 time 2 pv e5e8 f5e4 g2h2
info depth 3 seldepth 4 multipv 1 score cp 61 nodes 288 nps 144000 tbhits 0 time 2 pv e5a5 f5e4 g2f2 e4c2
info depth 4 seldepth 7 multipv 1 score cp 37 nodes 832 nps 416000 tbhits 0 time 2 pv e5e1 f5d3 e1c1 f4e3
info depth 5 seldepth 7 multipv 1 score cp 57 nodes 1614 nps 538000 tbhits 0 time 3 pv e5a5 f5e6 a5a3 e6d5 g2f2
info depth 6 seldepth 7 multipv 1 score cp 77 nodes 2312 nps 578000 tbhits 0 time 4 pv e5e8 f4g5 e8f8 f5e6 f8f1
info depth 7 seldepth 9 multipv 1 score cp 52 nodes 5772 nps 824571 tbhits 0 time 7 pv e5e2 f4g5 e2e3 f5c8 e3e8 c8f5 e8b8
info depth 8 seldepth 13 multipv 1 score cp 79 nodes 7301 nps 912625 tbhits 0 time 8 pv e5e2 f5e4 g2f2 e4f5 e2e3 f5b1 e3e8
info depth 9 seldepth 14 multipv 1 score cp 94 nodes 11536 nps 1048727 tbhits 0 time 11 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5c2 a4d4 c2g6 g2h2
info depth 10 seldepth 16 multipv 1 score cp 104 nodes 14038 nps 1079846 tbhits 0 time 13 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5c2 a4d4 c2g6 d4g4 g5h5 g2h2
info depth 11 seldepth 20 multipv 1 score cp 57 nodes 30150 nps 1206000 tbhits 0 time 25 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5c2 a4d4 g5h5 d4d5 h5g6 g2h2 g6f6 h2g1 c2h7
info depth 12 seldepth 19 multipv 1 score cp 45 nodes 47101 nps 1239500 tbhits 0 time 38 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5e6 a4d4 e6f5 d4c4 f5e6 c4c5 e6f5 c5b5 g5f6 b5b6 f6e5
info depth 13 seldepth 23 multipv 1 score cp 35 nodes 72084 nps 1287214 tbhits 0 time 56 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5e6 a4d4 e6f5 d4c4 f5e6 c4c5 e6f5 g2h2 g5f6 c5a5 f6g5 a5a4 g5h5 a4b4
info depth 14 seldepth 27 multipv 1 score cp 48 nodes 85013 nps 1288075 tbhits 0 time 66 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 f2g2 f5d7 a4a5 d7f5 a5b5 g5f6 g2h2 f6g5 b5c5 g5f6 c5c6 f6g5 c6d6 f5e4 d6d7
info depth 15 seldepth 27 multipv 1 score cp 32 nodes 116958 nps 1314134 tbhits 0 time 89 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 a4a3 g5f4 a3e3 f4g5 e3b3 g5f6 f2e1 f6g5 b3f3 f5e4 f3e3 g5f4
info depth 16 seldepth 23 multipv 1 score cp 26 nodes 170970 nps 1346220 tbhits 0 time 127 pv e5a5 f5e4 g2f2 e4f5 a5a4 f4g5 a4a3 g5f4 a3f3 f4e4 f3b3 e4e5 f2g2 e5f4 g2h2 f4g5 b3b4 f5e6 b4b2 e6d7 b2b6
info depth 17 seldepth 28 multipv 1 score cp 26 nodes 196258 nps 1362902 tbhits 0 time 144 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6e5 a3b3 e5f6 f2g2 f5d7 b3f3 d7f5 f3f1 f6g5 f1c1 f5d7 g2h2 d7f5 c1c4 f5d7
info depth 18 seldepth 21 multipv 1 score cp 26 nodes 205592 nps 1379812 tbhits 0 time 149 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6e5 a3b3 e5f6 f2g2 f5e4 g2h2 e4f5 b3b4 f6g5 b4b6 f5d7 b6d6 d7f5 d6c6
info depth 19 seldepth 21 multipv 1 score cp 26 nodes 227297 nps 1394460 tbhits 0 time 163 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5g6 b3f3 g6f6 f2g2 f6g5 f3f1 f5e6 f1c1 e6d7 c1d1
info depth 20 seldepth 26 multipv 1 score cp 31 nodes 255265 nps 1426061 tbhits 0 time 179 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 f5e4 b3b4 e4f5 f2g2 f5e6 b4b6 e6f5 g2h2 f5d7 b6b4 d7e6 b4b2 e6c8 b2g2 g5f4 g2g7
info depth 21 seldepth 25 multipv 1 score cp 34 nodes 279539 nps 1426219 tbhits 0 time 196 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 f5e4 b3b4 e4f5 f2g2 f5e6 b4b6 e6f5 g2h2 f5d7 b6b2 g5f4 b2f2 f4g5 f2g2 g5f4 g2g6 d7f5 g6c6
info depth 22 seldepth 29 multipv 1 score cp 41 nodes 304492 nps 1422859 tbhits 0 time 214 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f4 b3b4 f4g5 f2g2 f5d7 b4b6 d7f5 b6d6 g5f4 g2h2 f4g5 d6d1 g5f4 d1c1 f4g5
info depth 23 seldepth 32 multipv 1 score cp 25 nodes 445726 nps 1451876 tbhits 0 time 307 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f4 b3b4 f4g5 f2g2 f5d7 b4c4 d7e6 c4c5 e6f5 c5c1 f5e6 g2h2 e6d7 c1g1 g5f6 g1d1 d7f5 d1c1 f6g5 c1c7 f5e6 c7a7 e6f5 a7a3
info depth 24 seldepth 32 multipv 1 score cp 25 nodes 476351 nps 1456730 tbhits 0 time 327 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f4 b3b4 f4g5 f2g2 f5d7 b4b3 d7f5 b3b6 f5e4 g2g1 e4f5 g1h2 g5f4 b6d6 f4g5 d6d1 g5f6 d1g1 f5e6 g1g2 e6d7 g2a2 f6g5
info depth 25 seldepth 31 multipv 1 score cp 25 nodes 493468 nps 1468654 tbhits 0 time 336 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f4 b3b4 f4g5 f2g2 f5d7 b4b3 d7f5 b3b6 f5e4 g2h2 e4f5 b6b4 f5d7 b4b1 d7f5 b1c1 f5d7 c1d1 d7f5
info depth 26 seldepth 30 multipv 1 score cp 30 nodes 631823 nps 1497210 tbhits 0 time 422 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f4 b3b4 f4g5 f2g2 f5d7 b4b3 d7f5 b3b6 f5e4 g2h2 e4f5 b6c6 f5d7 c6c4 d7f5 c4c1 g5f4 c1g1 f5d7 g1g8 d7f5
info depth 27 seldepth 32 multipv 1 score cp 33 nodes 785019 nps 1498127 tbhits 0 time 524 pv e5a5 f4g5 g2f2 g5f6 a5a3 f6g5 a3b3 g5f6 b3f3 f6e5 f2e3 f5e6 e3e2 e6f5 f3b3 f5d7 e2f2 e5f4 b3d3 d7f5 d3d4 f4g5 f2g2 f5e6 g2h2 e6f5 d4d1 g5f4
info depth 28 seldepth 34 multipv 1 score cp 58 nodes 1174553 nps 1494342 tbhits 0 time 786 pv e5a5 f5e4 g2f2 e4f5 a5a3 f4g5 a3f3 f5e4 f3e3 e4b1 f2g1 b1f5 g1g2 g5f4 e3b3 f4g5 g2h2 f5e6 b3c3 e6f5 c3c1 g5g6 c1c5 g6g5 c5b5 g5f6 b5a5 f6g6
info depth 29 seldepth 37 multipv 1 score cp 60 nodes 1415863 nps 1499854 tbhits 0 time 944 pv e5a5 f5e4 g2f2 e4f5 a5a3 f4g5 a3f3 f5e4 f3e3 e4b1 f2g1 b1f5 g1g2 g5f4 e3b3 f4g5 g2h2 f5e6 b3b6 e6d7 b6b4 d7c8 b4b5 c8f5 b5a5 g5f6 a5a6 f6g5 a6a4 f5d7 a4c4
info depth 30 seldepth 39 multipv 1 score cp 30 nodes 3327469 nps 1575506 hashfull 48 tbhits 0 time 2112 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 g2h2 g6g5 d5b5 g5g6 b5c5 g6g5 c5c1 f5d7 c1c3 d7f5 c3f3 f5e4 f3b3 e4f5 h2g1 f5c2 b3f3 c2e4 f3e3 g5f4 g1f2
info depth 31 seldepth 39 multipv 1 score cp 30 nodes 3391477 nps 1577431 hashfull 50 tbhits 0 time 2150 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 g2h2 g6g5 d5b5 g5g6 b5c5 g6g5 h2g2 g5g6 c5c6 g6g5 c6c3 g5f4 g2f2 f5h7 c3f3 f4e5 f3a3 h7f5 a3e3 e5f4 e3f3 f4g5 f3a3
info depth 32 seldepth 36 multipv 1 score cp 30 nodes 3440675 nps 1579015 hashfull 50 tbhits 0 time 2179 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 g2h2 g6g5 d5b5 g5g6 b5c5 g6g5 h2g2 g5g6 c5c6 g6g5 c6c3 g5f4 g2f2 f5h7 c3f3 f4g5 f3a3 h7f5 a3c3 g5f4 c3f3 f4g5
info depth 33 seldepth 42 multipv 1 score cp 31 nodes 4116156 nps 1589863 hashfull 63 tbhits 0 time 2589 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 g2h2 g6g5 d5b5 g5g6 b5c5 g6g5 c5c3 f5h7 h2g1 h7f5 c3a3 g5g6 a3f3 g6g5 g1f2 f5e4 f3e3 g5f4 e3a3 e4f5 a3a4 f4g5
info depth 34 seldepth 37 multipv 1 score cp 31 nodes 4154642 nps 1591816 hashfull 64 tbhits 0 time 2610 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 g2h2 g6g5 d5b5 g5f4 b5b3 f4g5 b3c3 f5g6 c3c1 g6f5 c1g1 g5f6 g1e1 f6g5 e1c1 f5e6 c1c3 e6f5 h2g2 g5f4 c3c4 f4g5 c4b4
info depth 35 seldepth 41 multipv 1 score cp 31 nodes 4331004 nps 1592866 hashfull 68 tbhits 0 time 2719 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 d5a5 g6g5 a5c5 g5f6 c5c3 f6g5 c3e3 f5g6 g2g1 g5f4 g1f2 g6f5 e3f3 f4e5 f3b3 f5d7 f2g2 e5f4 b3b1 f4g5 b1a1 g5f4 a1c1
info depth 36 currmove e5e2 currmovenumber 2
info depth 36 currmove e5b5 currmovenumber 3
info depth 36 currmove e5d5 currmovenumber 4
info depth 36 currmove e5e1 currmovenumber 5
info depth 36 currmove e5e7 currmovenumber 6
info depth 36 currmove e5e8 currmovenumber 7
info depth 36 currmove e5c5 currmovenumber 8
info depth 36 currmove g2h2 currmovenumber 9
info depth 36 currmove g2f2 currmovenumber 10
info depth 36 currmove g2g1 currmovenumber 11
info depth 36 currmove e5e3 currmovenumber 12
info depth 36 currmove g2h1 currmovenumber 13
info depth 36 currmove e5e6 currmovenumber 14
info depth 36 currmove e5e4 currmovenumber 15
info depth 36 currmove g2f1 currmovenumber 16
info depth 36 currmove e5f5 currmovenumber 17
info depth 36 seldepth 45 multipv 1 score cp 30 nodes 4882901 nps 1590521 hashfull 77 tbhits 0 time 3070 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 d5a5 g6g5 a5c5 g5f6 c5c3 f6g5 c3e3 f5g6 g2g1 g5f4 g1f2 g6f5 e3f3 f4g5 f3b3 f5e6 b3a3 g5f4 a3a4 f4g5 f2g2 e6c8 a4c4 c8e6 c4d4
info depth 37 currmove e5a5 currmovenumber 1
info depth 37 currmove e5f5 currmovenumber 2
info depth 37 currmove e5e2 currmovenumber 3
info depth 37 currmove e5d5 currmovenumber 4
info depth 37 currmove e5c5 currmovenumber 5
info depth 37 currmove e5b5 currmovenumber 6
info depth 37 currmove e5e8 currmovenumber 7
info depth 37 currmove e5e7 currmovenumber 8
info depth 37 currmove e5e1 currmovenumber 9
info depth 37 currmove g2f2 currmovenumber 10
info depth 37 currmove g2g1 currmovenumber 11
info depth 37 currmove g2h1 currmovenumber 12
info depth 37 currmove g2h2 currmovenumber 13
info depth 37 currmove e5e6 currmovenumber 14
info depth 37 currmove e5e4 currmovenumber 15
info depth 37 currmove g2f1 currmovenumber 16
info depth 37 currmove e5e3 currmovenumber 17
info depth 37 seldepth 46 multipv 1 score cp 30 nodes 5718517 nps 1604522 hashfull 84 tbhits 0 time 3564 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4d4 g5h5 d4d5 h5g6 d5a5 f5e4 g2h2 e4f5 a5b5 g6g5 b5c5 g5g6 c5c4 g6h5 c4c3 h5g5 c3f3 f5e6 f3d3 e6f5 d3c3 g5f4 h2g2 f5e4 g2f2 e4f5 c3f3 f4g5 f3b3 f5g6 b3b5 g6f5
info depth 38 currmove e5a5 currmovenumber 1
info depth 38 currmove e5e2 currmovenumber 2
info depth 38 currmove e5d5 currmovenumber 3
info depth 38 currmove e5e8 currmovenumber 4
info depth 38 currmove e5c5 currmovenumber 5
info depth 38 currmove e5e7 currmovenumber 6
info depth 38 currmove e5b5 currmovenumber 7
info depth 38 currmove e5e1 currmovenumber 8
info depth 38 currmove g2h2 currmovenumber 9
info depth 38 currmove g2f2 currmovenumber 10
info depth 38 currmove g2g1 currmovenumber 11
info depth 38 currmove g2f1 currmovenumber 12
info depth 38 currmove e5e6 currmovenumber 13
info depth 38 currmove g2h1 currmovenumber 14
info depth 38 currmove e5e3 currmovenumber 15
info depth 38 currmove e5e4 currmovenumber 16
info depth 38 currmove e5f5 currmovenumber 17
info depth 38 seldepth 44 multipv 1 score cp 30 nodes 5949869 nps 1599857 hashfull 86 tbhits 0 time 3719 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2f2 e4f5 b3b5 g5f4 f2g2 f5e4 g2h2 e4f5 b5b6 f4g5 b6b3 g5f4 b3c3 f4g5 h2g2 f5g6 g2f2 g6f5 c3c5 g5g6 f2g2 g6g5 c5a5 g5f4 a5a4 f4g5 a4b4 f5e6
info depth 39 currmove e5a5 currmovenumber 1
info depth 39 currmove e5e2 currmovenumber 2
info depth 39 currmove e5e1 currmovenumber 3
info depth 39 currmove e5b5 currmovenumber 4
info depth 39 currmove e5d5 currmovenumber 5
info depth 39 currmove e5e8 currmovenumber 6
info depth 39 currmove e5e7 currmovenumber 7
info depth 39 currmove e5c5 currmovenumber 8
info depth 39 currmove g2f2 currmovenumber 9
info depth 39 currmove g2g1 currmovenumber 10
info depth 39 currmove g2h2 currmovenumber 11
info depth 39 currmove e5e3 currmovenumber 12
info depth 39 currmove g2h1 currmovenumber 13
info depth 39 currmove e5e4 currmovenumber 14
info depth 39 currmove g2f1 currmovenumber 15
info depth 39 currmove e5e6 currmovenumber 16
info depth 39 currmove e5f5 currmovenumber 17
info depth 39 seldepth 43 multipv 1 score cp 30 nodes 6310471 nps 1606126 hashfull 91 tbhits 0 time 3929 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2f2 e4f5 b3b5 g5f4 f2g2 f5e4 g2h2 e4f5 b5a5 f4g5 a5d5 g5f4 d5d4 f4g5 d4d6 f5c2 d6b6 c2f5 b6b3 g5f4 b3c3 f4g5 h2g2 f5e4 g2g1 e4f5 c3c5 g5f4 g1g2 f5e4 g2f2
info depth 40 currmove e5a5 currmovenumber 1
info depth 40 currmove e5e2 currmovenumber 2
info depth 40 currmove e5e1 currmovenumber 3
info depth 40 currmove e5e7 currmovenumber 4
info depth 40 currmove e5d5 currmovenumber 5
info depth 40 currmove e5b5 currmovenumber 6
info depth 40 currmove e5e8 currmovenumber 7
info depth 40 currmove e5c5 currmovenumber 8
info depth 40 currmove e5e3 currmovenumber 9
info depth 40 currmove g2h2 currmovenumber 10
info depth 40 currmove g2g1 currmovenumber 11
info depth 40 currmove g2f2 currmovenumber 12
info depth 40 currmove e5e6 currmovenumber 13
info depth 40 currmove g2h1 currmovenumber 14
info depth 40 currmove g2f1 currmovenumber 15
info depth 40 currmove e5e4 currmovenumber 16
info depth 40 currmove e5f5 currmovenumber 17
info depth 40 seldepth 43 multipv 1 score cp 30 nodes 7124810 nps 1620748 hashfull 99 tbhits 0 time 4396 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2h2 e4h7 b3c3 h7f5 c3f3 f5d7 f3b3 d7f5 b3c3 g5f4 c3c4 f4g5 c4a4 f5d7 a4a5 d7f5 h2g1 g5g6 g1g2 f5e4 g2f2 e4f5 a5a3 g6g5 a3f3 f5c2 f3e3 c2f5 e3a3 f5g6 a3a4
info depth 41 currmove e5a5 currmovenumber 1
info depth 41 currmove e5e2 currmovenumber 2
info depth 41 currmove e5e1 currmovenumber 3
info depth 41 currmove e5b5 currmovenumber 4
info depth 41 currmove e5d5 currmovenumber 5
info depth 41 currmove e5e8 currmovenumber 6
info depth 41 currmove e5e7 currmovenumber 7
info depth 41 currmove e5c5 currmovenumber 8
info depth 41 currmove e5e4 currmovenumber 9
info depth 41 currmove g2f2 currmovenumber 10
info depth 41 currmove g2g1 currmovenumber 11
info depth 41 currmove g2f1 currmovenumber 12
info depth 41 currmove e5e3 currmovenumber 13
info depth 41 currmove e5e6 currmovenumber 14
info depth 41 currmove g2h1 currmovenumber 15
info depth 41 currmove g2h2 currmovenumber 16
info depth 41 currmove e5f5 currmovenumber 17
info depth 41 seldepth 50 multipv 1 score cp 24 nodes 11320625 nps 1688385 hashfull 145 tbhits 0 time 6705 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2h2 e4f5 b3b6 f5c2 b6b4 c2g6 b4g4 g5h5 h2g2 g6f5 g4g8 h5h6 g2f3 f5h3 f3f4 h3f1 g8h8 h6g6 h8h4 g6f6 h4h1 f1c4 h1h6 f6e7 f4e5 e7d7 h6d6 d7e8 d6c6 c4f7 e5d6 f7g6 c6c8 e8f7
info depth 42 currmove e5a5 currmovenumber 1
info depth 42 currmove e5e2 currmovenumber 2
info depth 42 currmove e5b5 currmovenumber 3
info depth 42 currmove e5c5 currmovenumber 4
info depth 42 currmove e5e8 currmovenumber 5
info depth 42 currmove e5d5 currmovenumber 6
info depth 42 currmove e5e7 currmovenumber 7
info depth 42 currmove e5e1 currmovenumber 8
info depth 42 currmove g2h2 currmovenumber 9
info depth 42 currmove e5e4 currmovenumber 10
info depth 42 currmove g2f2 currmovenumber 11
info depth 42 currmove g2h1 currmovenumber 12
info depth 42 currmove e5e3 currmovenumber 13
info depth 42 currmove e5e6 currmovenumber 14
info depth 42 currmove g2g1 currmovenumber 15
info depth 42 currmove g2f1 currmovenumber 16
info depth 42 currmove e5f5 currmovenumber 17
info depth 42 seldepth 52 multipv 1 score cp 22 nodes 16348900 nps 1738504 hashfull 204 tbhits 0 time 9404 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2h2 e4f5 b3b5 g5f4 b5b4 f4g5 b4a4 f5d7 a4a5 d7f5 a5c5 g5f4 c5c4 f4g5 c4c1 g5f4 c1f1 f4g5 f1g1 g5f4 g1g7 f5e6 g7a7 e6f5 h2g2 f4g5 a7a3 f5e4 g2f2 e4f5 a3c3 f5e6 c3c5 g5f4 f2g2 e6f5 c5f5 f4f5 g2f3 f5g5
info depth 43 currmove e5a5 currmovenumber 1
info depth 43 currmove e5e2 currmovenumber 2
info depth 43 currmove e5e1 currmovenumber 3
info depth 43 currmove e5c5 currmovenumber 4
info depth 43 currmove e5b5 currmovenumber 5
info depth 43 currmove e5e7 currmovenumber 6
info depth 43 currmove e5d5 currmovenumber 7
info depth 43 currmove e5e8 currmovenumber 8
info depth 43 currmove g2g1 currmovenumber 9
info depth 43 currmove e5e3 currmovenumber 10
info depth 43 currmove g2f2 currmovenumber 11
info depth 43 currmove g2h2 currmovenumber 12
info depth 43 currmove e5e6 currmovenumber 13
info depth 43 currmove e5e4 currmovenumber 14
info depth 43 currmove g2h1 currmovenumber 15
info depth 43 currmove g2f1 currmovenumber 16
info depth 43 currmove e5f5 currmovenumber 17
info depth 43 seldepth 44 multipv 1 score cp 22 nodes 16792264 nps 1742840 hashfull 207 tbhits 0 time 9635 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2h2 e4f5 b3b5 g5f4 b5a5 f4g5 a5c5 g5f4 c5c3 f4g5 c3c6 g5f4 c6h6 f4g5 h6h8 f5e6 h2g2 e6d5 g2g1 d5e6 g1h2 e6f5 h8d8 f5c2 d8g8 c2g6 h2g2 g5h5 g8c8 h5g5 c8c5 g6f5
info depth 44 currmove e5a5 currmovenumber 1
info depth 44 seldepth 44 multipv 1 score cp 22 nodes 17403430 nps 1740168 hashfull 219 tbhits 0 time 10001 pv e5a5 f5e4 g2h2 e4f5 a5a4 f4g5 a4b4 f5c8 h2g2 c8f5 b4b3 f5e4 g2h2 e4f5 b3b5 g5f4 b5a5 f4g5 a5c5 g5f4 c5c3 f4g5 c3c6 g5f4 c6h6 f4g5 h6h8 f5e6 h2g2 e6d5 g2g1 d5e6 g1h2 e6f5 h8d8 f5c2 d8g8 c2g6 h2g2 g5h5 g8c8 h5g5 c8c5 g6f5
bestmove e5a5 ponder f5e4

If something's wrong with that I will need further info what to change.

**Comment by 0zymandia2** [comment]
From what I see in the pv, the first move is Ra5, not giving up the exchange and, subsequently, forcing a stalemate. Instead, it moves the Rook away, calculating an end score of just 22 centipawns, when it should be 384.

But, at least on command-line, the final PV doesn't hang pieces.

**Comment by 0zymandia2** [comment]
info... like info about what to change in the code? Wouldn't know where to start.
